### ISSUE TITLE
Kosong?

### ISSUE THREAD

**Issue by mzaini30** [lutfianam/linaxsec-v0.1#3]
https://github.com/lutfianam/linaxsec-v0.1/blob/6f2a72c01c63412689993eafa6e82fc3cbe28d4c/assets/index.php#L1

**Comment by lutfianam** [comment]
Maaf kang code belum sepenuhnya terupload semua, soalnya saya uploadnya manual lewat browser.

**Comment by mzaini30** [comment]
> Maaf kang code belum sepenuhnya terupload semua, soalnya saya uploadnya manual lewat browser.

Kamu pakai Windows, Linux, atau Android?

**Comment by lutfianam** [comment]
Android kang, speak rendah. Mau install termux not support:'( mau install gnuroot, android jadi lelet:V

**Comment by mzaini30** [comment]
> Android kang, speak rendah. Mau install termux not support:'( mau install gnuroot, android jadi lelet:V

Nggak bisa install Termux?

**Comment by lutfianam** [comment]
Ngak bisa kang, hp saya masih kitkat.

**Comment by mzaini30** [comment]
> Ngak bisa kang, hp saya masih kitkat.

Coba download lewat Google. Misalnya di APK Pure

**Comment by lutfianam** [comment]
Udah saya coba kang tetep ngak bisa,walaupun bisa di install di kitkat aplikasi tetap ngak bisa di buka
