### ISSUE TITLE
Nggak perlu pakai ?>

### ISSUE THREAD

**Issue by mzaini30** [lutfianam/linaxsec-v0.1#4]
https://github.com/lutfianam/linaxsec-v0.1/blob/6f2a72c01c63412689993eafa6e82fc3cbe28d4c/config.php#L54

Sebenarnya sih file PHP tu nggak perlu diakhirin dengan `?>`

**Comment by lutfianam** [comment]
Berarti saat saya membuka <?php kalau tidak di akhiri ngk papa kang?

**Comment by mzaini30** [comment]
> Berarti saat saya membuka <?php kalau tidak di akhiri ngk papa kang?

Iya. Coba aja buka source codenya Codeigniter untuk contohnya

Dan setauku memang sih direkomendasikannya nggak perlu pakai `?>`. Coba googling lagi.
